name: Code analysis

on:
  push:
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"
jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.3
          extensions: mbstring, dom, fileinfo, mysql
          tools: phpcs
      - name: PHP_CodeSniffer
        run: phpcs --extensions=php app
